Log4j most commonly shared indicators (Dec 10-13 2022)
refractionPOINT/rules pull request #6
Opened 2021-12-13 16:23 UTC by gio-pecora

Guidance required for adding the following hosted YARA rule into the template: https://github.com/Neo23x0/signature-base/blob/master/yara/expl_log4j_cve_2021_44228.yar

2021-12-13 18:35 UTC, maximelb requested changes

2021-12-13 18:35 UTC, maximelb commented on Emerging_Threats/log4j.yml
> +        path: event/NETWORK_ACTIVITY/?/DESTINATION/IP_ADDRESS
Do we only care about Destination?

I think what you want is this:
```suggestion
        path: event/NETWORK_ACTIVITY/?/IP_ADDRESS
```

2021-12-13 18:35 UTC, maximelb commented on Emerging_Threats/log4j.yml
> +      - ONGOING_IDENTITY
```suggestion
      - ONGOING_IDENTITY
      - CODE_IDENTITY
```

2021-12-15 16:38 UTC, gio-pecora reviewed
Approved

2021-12-16 16:52 UTC, gio-pecora commented
https://github.com/refractionPOINT/rules/blob/log4j/Emerging_Threats/log4j.yml

2021-12-16 16:53 UTC, gio-pecora reviewed
Template optimised as requested

2021-12-16 17:05 UTC, gio-pecora commented
Closed by mistake

2021-12-16 17:05 UTC, maximelb approved these changes

2021-12-16 17:06 UTC, merged